version: "3.8"

services:
  app:
    container_name: my-app
    build:
      context: ./../
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - postgres
    ports:
      - ${HOST_HTTP_PORT}:8080
  postgres:
    container_name: m-postgres
    build:
      context: ./postgres

    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data: